Разметка страниц на проверку
htmlacademy-htmlcss/2168343-sedona-35 pull request #1
Opened 2022-09-27 17:20 UTC by drajejke

2022-09-28 12:03 UTC, maxzbest requested changes

2022-09-28 12:03 UTC, maxzbest commented on catalog.html
> +            <a class="navigation-link" href="#"><span class="visually-hidden">Лайки</span></a>
В макете написано "Избранное"

2022-09-28 12:03 UTC, maxzbest commented on index.html
> +        <p><strong>Седона — небольшой городок в Аризоне,<br>
Можно h3 сделать

2022-09-28 12:03 UTC, maxzbest commented on index.html
> +        <h2 class="visually-hidden">Рекоммендуем</h2>
```suggestion
        <h2 class="visually-hidden">Рекомендуем</h2>
```

2022-09-28 12:03 UTC, maxzbest commented on index.html
> +            <h3>ЖИЛЬЁ</h3>
Везде пишем капитализированными текстами (только первая буква заглавная), потом уже стилями будем делать uppercase

2022-09-28 12:03 UTC, maxzbest commented on index.html
> +          <label for="subscribe-email">email</label>
Тут можно обойтись без лейбла, ну или скрыть тогда уж, в макете есть только инпут с плейсхолдером

2022-09-28 12:03 UTC, maxzbest commented on catalog.html
> +      <header class="inner-header">
Давай уберём тут хедер, сделаем внутри main три секции, 1я это загаловок+хлебныеКрошки+фильтры с кнопками, 2я это найдено и сортировки+список карточек+пагинация, 3я подписка на рассылку

2022-09-28 12:03 UTC, maxzbest commented on catalog.html
> +          </fieldset>
Инпуты со стоимостью пропустил

2022-09-28 12:03 UTC, maxzbest commented on catalog.html
> +          <p class="search-results">Найдено гостиниц:<output name="result"></output>38</p>
Это будет загаловок для второй секции

2022-09-28 12:03 UTC, maxzbest commented on catalog.html
> +        <a class="button-light" href="#">
Тут переходов на другую страницу не предполагается, давай сделаем кнопками

2022-09-28 12:03 UTC, maxzbest commented on catalog.html
> +            <a class="additional-button button" href="#">В избранное</a>
Сделать кнопкой

2022-09-28 12:03 UTC, maxzbest commented on catalog.html
> +          <li class="pagination-item">
Тут давай оставим просто спан с многоточием

2022-09-29 08:01 UTC, drajejke commented on catalog.html
> +            <a class="additional-button button" href="#">В избранное</a>
У меня возник вопрос. А что если js не отработает по кнопкам "Подробнее" и "В избранное". Если бы была ссылка то, перешел бы все равно пользователей на страницу. Или здесь лучше кнопкой делать все таки?

2022-09-30 05:12 UTC, merged