Базовая стилизация всех страниц
htmlacademy-htmlcss/2168343-sedona-35 pull request #3
Opened 2022-10-09 07:30 UTC by drajejke

2022-10-09 20:06 UTC, maxzbest requested changes

2022-10-09 20:06 UTC, maxzbest commented on catalog.html
> +          <button class="button-invis button" type="reset">Сбросить</button>
button-invis сокращать названия плохая практика

2022-10-09 20:06 UTC, maxzbest commented on catalog.html
> +          <output class="search-result" name="result">38</output>
Класс совпадает с родительским, надо сделать разные

2022-10-09 20:06 UTC, maxzbest commented on catalog.html
> +        <div class="search-result">
Класс совпадает с родительским, надо сделать разные

2022-10-09 20:06 UTC, maxzbest commented on catalog.html
> +        <ul class="hotel-cards">
hotel-card-list

2022-10-09 20:06 UTC, maxzbest commented on catalog.html
> +          <li class="hotel-card">
hotel-card-item

2022-10-09 20:06 UTC, maxzbest commented on catalog.html
> +            <button class="button button-blue" type="button">В избранное</button>
button-blue сегодня в макете она синяя, а завтра дизайнер решит что лучше оранжевая вписывается, придётся везде переименовывать, чтобы этого избежать – лучше не использовать названия в стиле "красный" или "третий" и т.п. Конкретно в этом случае можно написать button-color

2022-10-09 20:06 UTC, maxzbest commented on styles/styles.css
> +  color: #000000;
Можно писать короче, вот так #000

2022-10-09 20:06 UTC, maxzbest commented on styles/styles.css
> +  background-color: #756157;
Давай вынесем цвета в css-переменные, если про них не рассказывали ещё, то гугл подскажет что это такое

2022-10-09 20:06 UTC, maxzbest commented on styles/styles.css
> +
Лишняя пустая строка

2022-10-09 20:06 UTC, maxzbest commented on styles/styles.css
> +
Лишняя пустая строка

2022-10-09 20:06 UTC, maxzbest commented on styles/styles.css
> +
Лишняя пустая строка

2022-10-09 20:06 UTC, maxzbest commented on styles/styles.css
> +
Лишняя пустая строка

2022-10-09 20:06 UTC, maxzbest commented on styles/styles.css
> +
Лишняя пустая строка

2022-10-09 20:06 UTC, maxzbest commented on styles/styles.css
> +  height: 414.86px;
Придерживаемся целочисленных значений, и желательно чётных, а ещё лучше кратных 4м или 8ми, тут можно оставить 414

2022-10-09 20:06 UTC, maxzbest commented on styles/styles.css
> +.subscribe p {
Избегаем селекторов по тегу

2022-10-09 20:06 UTC, maxzbest commented on styles/styles.css
> +  background-color: #F2F2F2;
Если начал строчными описывать, везде придерживайся одного стиля написания

2022-10-09 20:06 UTC, maxzbest commented on styles/styles.css
> +  font-weight: 400;
400 это дефлотное значение, его не нужно писать

2022-10-10 18:02 UTC, drajejke commented on styles/styles.css
> +  font-weight: 400;
только у меня селектор .filters задает font-weight: 700, а для .cotalog-filter-item нужно 400. Вот и прописал. Или я, что то не так понял?

2022-10-10 20:39 UTC, maxzbest requested changes

2022-10-10 20:39 UTC, maxzbest commented on styles/styles.css
>    background-color: #756157;
Эти цвета, как и все остальные, тоже в переменные

2022-10-10 20:39 UTC, maxzbest commented on styles/styles.css
> +:root {
Ну нужно каждый раз писать :root, достаточно один раз вызвать объект,

:root {
  --color-black: #000;
  --color-white: #fff;
  ...
}

2022-10-10 20:40 UTC, maxzbest commented
<img width="1739" alt="image" src="https://user-images.githubusercontent.com/36470352/194949070-e174a823-68a3-4d5e-90a9-8b39f17a4741.png">

Заметил странные изменения в свгшках, а зачем так было сделано?

2022-10-12 12:30 UTC, maxzbest commented on styles/styles.css
> +  --color-background-light-blue2: rgba(131, 179, 211, 0.2);
--color-background-light-blue2 плохое название, если описываем одинаковые цвета, отличающиеся друг от друга только значением альфа-канала, то именно эту цифру и добавляем через дефис, будет вот так:
  --color-background-light-blue-12: rgba(131, 179, 211, 0.12);
  --color-background-light-blue-20: rgba(131, 179, 211, 0.2);

2022-10-12 12:30 UTC, maxzbest commented on styles/styles.css
> +  --color-background-ininvisible: rgba(255, 255, 255, 0);
ininvisible похоже на опечатку

2022-10-13 07:28 UTC, maxzbest approved these changes

2022-10-13 07:28 UTC, merged