Сетка страниц и крупных блоков на флексах
htmlacademy-htmlcss/2168343-sedona-35 pull request #4
Opened 2022-10-18 10:21 UTC by drajejke

---
:mortar_board: [Сетка страниц и крупных блоков на флексах](https://up.htmlacademy.ru/htmlcss/35/user/2168343/tasks/10)

2022-10-20 13:33 UTC, maxzbest requested changes

2022-10-20 13:33 UTC, maxzbest commented on catalog.html
> +          <svg width="140" height="70" fill="none" xmlns="http://www.w3.org/2000/svg">
Выглядит очень массивно, почему именно такой способ подключения свг тут заюзал?

2022-10-20 13:33 UTC, maxzbest commented on styles/styles.css
>  body {
<img width="416" alt="image" src="https://user-images.githubusercontent.com/36470352/196945812-1bbf3023-1b83-40d8-beef-7db669e17999.png">

Много лишних стилей тут описано, см. скрин, отключил лишние свойства и в браузере ничего не поменялось

2022-10-20 13:33 UTC, maxzbest commented on styles/styles.css
> +  height: 100%;
Кажется свойство ни на что не влияет

2022-10-20 13:33 UTC, maxzbest commented on styles/styles.css
> +/*.visually-hidden{
Забыл раскомментить?

2022-10-20 13:33 UTC, maxzbest commented on styles/styles.css
> +  flex-grow: 1;
Лишнее свойство

2022-10-20 13:33 UTC, maxzbest commented on styles/styles.css
> +  width: 1280px;
Здесь ширину нужно выставить 1200 пихулей

2022-10-20 13:33 UTC, maxzbest commented on styles/styles.css
> +  width: 1200px;
После того, как в body будет установлена ширина 1200, тут уже не нужны становятся свойства width и margin

2022-10-20 13:33 UTC, maxzbest commented on styles/styles.css
> +  justify-content: space-between;
Ничего не меняется сейчас при этом свойстве, нужно у дочерних элементов поубирать отступы, если хочется, чтобы работало space-between

2022-10-20 13:33 UTC, maxzbest commented on styles/styles.css
> +  align-items: flex-start;
Это свойство тоже можно убрать, ничего не меняется от него тут

2022-10-20 13:33 UTC, maxzbest commented on styles/styles.css
>    width: 1200px;
Лишнее свойство

2022-10-20 13:33 UTC, maxzbest commented on styles/styles.css
> +  margin: 0 auto;
Лишнее свойство

2022-10-20 13:33 UTC, maxzbest commented on styles/styles.css
> +  background-color: var(--color-white);
Выставление белого цвета давай везде уберём и будем в случае с ним опираться на белый фон указанный в body

2022-10-20 13:33 UTC, maxzbest commented on styles/styles.css
>    background-image: url(../images/index-background.jpg);
welcome to the gor.. тоже должно быть в этой картинке, а не отдельной свгшкой в разметке

2022-10-20 13:33 UTC, maxzbest commented on styles/styles.css
>    color: var(--color-black);
Лишнее свойство

2022-10-20 13:33 UTC, maxzbest commented on styles/styles.css
>    background-color: var(--color-white);
Цвет фона у картинки делается на случай, если картинка не отобразилась, соответственно цвет этот должен быть подобран исходя из цветов на картинке, чтобы было плюс-минус похожее что-то

2022-10-20 13:33 UTC, maxzbest commented on styles/styles.css
> +.welcome-logo {
Селектор станет ненужным, после того как уберём свгшку из разметки

2022-10-20 13:33 UTC, maxzbest commented on styles/styles.css
> +  margin: 0;
Лишнее свойство

2022-10-20 13:33 UTC, maxzbest commented on styles/styles.css
>    font-size: 30px;
Стили для текста лучше указать дочернему тегу h3 через класс, как это сделано для description-text

2022-10-20 13:33 UTC, maxzbest commented on styles/styles.css
>    font-size: 30px;
И после этого в description-text станет лишним свойство text-transform: none;

2022-10-20 13:33 UTC, maxzbest commented on styles/styles.css
>    font-size: 30px;
И font-weight: 400; тоже

2022-10-20 13:33 UTC, maxzbest commented on styles/styles.css
> +  margin: 0;
Во всех списках поубирай вот эти обнуления отступов и прочее, вынеси отдельно наверх для всех списков, по тегу ul

2022-10-20 13:33 UTC, maxzbest commented on styles/styles.css
>    text-align: center;
Это свойство лучше в advantages-item перенести

2022-10-20 13:33 UTC, maxzbest commented on styles/styles.css
> +.advantages-list li:nth-child(4) {
Вот так через nth плохой вариант, завтра дизайнеру покажется более подходящим другое расположение и у нас всё поломается, сделай дополнительные классы для добавления цветастости

2022-10-20 13:33 UTC, maxzbest commented on styles/styles.css
>    text-align: center;
В айтем

2022-10-20 13:33 UTC, maxzbest commented on styles/styles.css
> +  width: 400px;
Попробуй поменять на flex-basis и подумать, в чём разница

2022-10-20 13:33 UTC, maxzbest commented on styles/styles.css
> +  padding: 96px 304px;
Если сделать padding: 96px 0px; ничего не поменяется

2022-10-20 13:33 UTC, maxzbest commented on styles/styles.css
>    line-height: 26px;
Эти три свойства можно убрать отсюда

2022-10-20 13:33 UTC, maxzbest commented on styles/styles.css
> -.search-hotel-buttom {
buttom надо поменять на button, где бы он ни был))

2022-10-20 13:33 UTC, maxzbest commented on styles/styles.css
>    width: 1200px;
Лишнее свойство

2022-10-20 13:33 UTC, maxzbest commented on styles/styles.css
> +  text-align: center;
Это свойство лучше прописать там где оно нужно, у дочерних элементов, а тут описать выравнивание флексом 
<img width="415" alt="image" src="https://user-images.githubusercontent.com/36470352/196960175-e4d19e2e-71f1-4f9a-b5aa-174e72dd4e95.png">

2022-10-20 13:33 UTC, maxzbest commented on styles/styles.css
> +  margin: 0;
Поубирай у отдельных классов обнуление внешних отступов у заголовков и вынеси наверх в селектор по тегу

2022-10-20 13:33 UTC, maxzbest commented on styles/styles.css
> +.page-footer {
У футера есть внутренний отступ по макету

2022-10-20 13:33 UTC, maxzbest commented on styles/styles.css
> +  width: 1200px;
Лишнее свойство

2022-10-20 13:33 UTC, maxzbest commented on styles/styles.css
> +  width: 142px;
Лишнее свойство

2022-10-20 13:33 UTC, maxzbest commented on styles/styles.css
> +  width: 142px;
+нет обнуления стилей списка, но мы его добавим сверху в селекторе по тегу

2022-10-20 13:33 UTC, maxzbest commented on styles/styles.css
> +  width: 720px;
Лишние свойства

2022-10-20 14:04 UTC, drajejke commented on catalog.html
> +          <svg width="140" height="70" fill="none" xmlns="http://www.w3.org/2000/svg">
Если подключаю, через тег img то буквы в логотипе становятся черными и  их не видно. Не понимаю в чем проблема, через svg все нормально. Аналогично с логотипом Welcome только он становиться невидимым.

2022-10-23 15:35 UTC, maxzbest requested changes

2022-10-23 15:35 UTC, maxzbest commented on styles/styles.css
> +
лишний отступ

2022-10-23 15:35 UTC, maxzbest commented on styles/styles.css
> +  border: 2px solid #E5E5E5;
цвет в переменную

2022-10-24 12:45 UTC, maxzbest approved these changes

2022-10-24 12:46 UTC, merged