Доделал 6 раздел
htmlacademy-htmlcss/2168343-sedona-35 pull request #5
Opened 2022-10-29 10:55 UTC by drajejke

2022-10-31 10:14 UTC, maxzbest requested changes

2022-10-31 10:14 UTC, maxzbest commented on styles/styles.css
> +.button-light-last {
Давай переделаем блок, нужно доабвить обёртку для кнопок, сделать её флекс-контейнером и отступ между кнопками регулировать с помощью свойства gap у флекс-контейнера, тогда можно будет удалить ещё и обнуление отступа для последней кнопки

2022-10-31 10:14 UTC, maxzbest commented on styles/styles.css
> +.button-light-last {
Спойлер:
<img width="955" alt="image" src="https://user-images.githubusercontent.com/36470352/198973513-9401dcd1-21f5-4a47-87f2-aa51fbabb706.png">

2022-10-31 10:14 UTC, maxzbest commented on styles/styles.css
> +.filtet-button-wrap .button-additional {
Ты тут полностью меняешь основные стили у класса на основе его вложенности в другой класс, нужно от этго везде избавляться, создавай отдельные классы

2022-10-31 10:14 UTC, maxzbest commented on styles/styles.css
> +.search-hotel .button {
аналогично

2022-10-31 10:14 UTC, maxzbest commented on styles/styles.css
>  .navigation-logo {
А у тебя лого норм отображается? У меня не отображалось, пока путь на `./images/logo.svg` не поменял

2022-10-31 10:14 UTC, maxzbest commented on styles/styles.css
> +  display: flex;
Я бы сюда ещё выравнивание по центру относительно поперечной оси добавил

2022-10-31 10:14 UTC, maxzbest commented on styles/styles.css
> +.navigation-user .navigation-link {
У этих не хватает иконок через background подключенных

2022-10-31 10:14 UTC, maxzbest commented on styles/styles.css
> +  min-width: 18px;
А почему через min высота и ширина? У блока же не подразумевается какое-то расширение, тут всегда будет иконка постоянного размера

2022-10-31 10:14 UTC, maxzbest commented on styles/styles.css
> +.navigation-user .navigation-link {
А вот здесь через вложенность вписывается, потому что лишь часть стилей от основных меняется

2022-10-31 10:14 UTC, maxzbest commented on styles/styles.css
>  .navigation-item .button {
А вот тут вложенность снова не вписывается, т.к. вообще всё меняешь.

В отдельный класс

2022-10-31 10:14 UTC, maxzbest commented on styles/styles.css
> +  padding-top: 51px;
Старайся придерживаться величин, кратных сетки, или хотя бы чётных.

Хорошие сетки обычно кратные 4м или 8ми пикселям

2022-10-31 10:14 UTC, maxzbest commented on styles/styles.css
> +  padding: 69px 290px 0;
Отступ плохо здесь такой указывать, попробуй удалить блок и посмотри как расположится оставшийся, отступа у него уже не окажется сверху, лучше у родителя отступ вертикальный сделать

2022-10-31 10:14 UTC, maxzbest commented on styles/styles.css
> +  padding: 69px 290px 0;
Спойлер:

<img width="849" alt="image" src="https://user-images.githubusercontent.com/36470352/198980943-b8847ad3-db2b-436b-a2d6-3d32943fa470.png">

2022-10-31 10:14 UTC, maxzbest commented on styles/styles.css
> +  margin-bottom: 25px;
Отступ тоже нехороший, давай сделаем родителя флекс-контейнером и через gap реализуем

2022-10-31 10:14 UTC, maxzbest commented on styles/styles.css
> +  padding: 0 274px 90px 275px;
И тут тоже отступы эти какие-то слишком уж большие, можно этот блок элегантнее обыграть, давай на созвон вынесем

2022-10-31 10:14 UTC, maxzbest commented on styles/styles.css
> +  padding-top: 103px;
Не первому элементу, а родителю этот внутренний вертикальный отступ напиши

А вместо margin-bottom пусть будет gap у родителя

2022-10-31 10:14 UTC, maxzbest commented on styles/styles.css
> +  padding-top: 92px;
Этот отступ тоже уйдёт, в целом странно, что он отличается от другого аналогичного

2022-10-31 10:14 UTC, maxzbest commented on styles/styles.css
> +  padding-top: 182px;
Внутренний родителю, внешний меняем на gap родителя

2022-10-31 10:14 UTC, maxzbest commented on styles/styles.css
> +  margin-bottom: 20px;
Можно в margin унести, `margin: 0 0 20px 0;`

2022-10-31 10:14 UTC, maxzbest commented on styles/styles.css
> +  margin-bottom: 54px;
Можно в margin унести

2022-10-31 10:14 UTC, maxzbest commented on styles/styles.css
> +.ubscribe-email {
Опечатка

2022-10-31 10:14 UTC, maxzbest commented on styles/styles.css
> +  width: 452px;
Кажется лишка, вижу что блок перекрываться другим начинает

422px

2022-10-31 10:14 UTC, maxzbest commented on styles/styles.css
> +  width: 452px;
Или у кнопки слишком большая ширина, нужно разобраться с этим

2022-10-31 10:14 UTC, maxzbest commented on styles/styles.css
> +  /* width: 549px; */
Лишний коммент?

2022-11-04 10:02 UTC, drajejke commented on styles/styles.css
>  .navigation-logo {
Да все сейчас хорошо отображается.

2022-11-04 11:02 UTC, drajejke commented on styles/styles.css
>  .navigation-item .button {
Проблема в том, что когда делаю через отдельный класс, он не переопределяет width, height и padding из свойства .navigation-user .navigation-link

2022-11-07 12:18 UTC, maxzbest approved these changes

2022-11-07 12:18 UTC, merged